### ISSUE TITLE
install.sh error

### ISSUE THREAD

**Issue by MasonQAQ** [qingxp9/PPPoE-Phisher#2]
脚本install.sh中 echo "require-pap\nlcp-echo-interval 10\nlcp-echo-failure 2" > /etc/ppp/pppoe-server-options 这一句不能输出作者想输出的换行符，应该在echo后加上-e参数，即：echo -e "require-pap\nlcp-echo-interval 10\nlcp-echo-failure 2" > /etc/ppp/pppoe-server-options

**Comment by qingxp9** [comment]
Sorry for that. 
I tested it using zsh and sh, but there are some different using bash.
So add the "-e" is better, I will update it.
