### ISSUE TITLE
在/bin/sh下面会多输出一个-e

### ISSUE THREAD

**Issue by Chinalover** [qingxp9/PPPoE-Phisher#3]
# echo -e "require-pap\nlcp-echo-interval 10\nlcp-echo-failure 2"
-e require-pap
lcp-echo-interval 10
lcp-echo-failure 2

最后看到freebuf下面的评论才知道配置文件错了。。半天嗅探不出来

**Comment by qingxp9** [comment]
Thanks.
Now, I have fixed it.
